title: DevelopmentMen
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: DevelopmentMen
  github: DevelopmentMen

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 1189
google_analytics: UA-NNNNNNNN-N
